// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"techunicorn.com/udc-core/gettingStarted/pkg/app/server/handlers"
	"techunicorn.com/udc-core/gettingStarted/pkg/impls/evcqrs"
	"techunicorn.com/udc-core/gettingStarted/pkg/impls/evcqrs/repos"
	"techunicorn.com/udc-core/gettingStarted/pkg/infra"
	"techunicorn.com/udc-core/gettingStarted/pkg/infra/config"
	"techunicorn.com/udc-core/gettingStarted/pkg/infra/lgr"
	"techunicorn.com/udc-core/gettingStarted/pkg/infra/psqldb"
	"techunicorn.com/udc-core/gettingStarted/pkg/infra/redisdb"
	"techunicorn.com/udc-core/gettingStarted/pkg/infra/trace"
	"techunicorn.com/udc-core/gettingStarted/pkg/infra/trace/appinsights"
	"techunicorn.com/udc-core/gettingStarted/pkg/infra/trace/jaeger"
	"techunicorn.com/udc-core/gettingStarted/pkg/infra/trace/promex"
)

// Injectors from wire.go:

// InitializeEvent creates an Event. It will error if the Event is staffed with
// a grumpy greeter.
func initializeAppCQRS() (*app, error) {
	loggerFactory, err := lgr.NewLoggerFactory()
	if err != nil {
		return nil, err
	}
	contextFactory := repos.NewContextFactory(loggerFactory)
	healthzHandler := handlers.NewHealthzHandler(contextFactory, loggerFactory)
	initializer := config.NewInitializer(loggerFactory)
	exporterOptions := config.NewAppInsightsExporterOptions(initializer)
	traceExporter, err := appinsights.NewTraceExporter(exporterOptions)
	if err != nil {
		return nil, err
	}
	jaegerExporterOptions := config.NewJaegerExporterOptions(initializer)
	jaegerTraceExporter, err := jaeger.NewJaegerTraceExporter(jaegerExporterOptions)
	if err != nil {
		return nil, err
	}
	promexTraceExporter, err := promex.NewTraceExporter()
	if err != nil {
		return nil, err
	}
	exporterList := infra.NewTraceExporterList(traceExporter, jaegerTraceExporter, promexTraceExporter, loggerFactory)
	options, err := config.NewTraceOptions(initializer)
	if err != nil {
		return nil, err
	}
	tracer, err := trace.NewTracer(exporterList, options, loggerFactory)
	if err != nil {
		return nil, err
	}
	databaseOptions := config.NewPSQLDBOptions(initializer)
	tracedDB, err := psqldb.NewDatabaseContext(tracer, databaseOptions)
	if err != nil {
		return nil, err
	}
	redisdbOptions := config.NewRedisOptions(initializer)
	client, err := redisdb.NewRedisContext(redisdbOptions, tracer)
	if err != nil {
		return nil, err
	}
	implementation := evcqrs.NewImplementation(tracedDB, client, loggerFactory)
	serverApp := newApp(healthzHandler, healthzHandler, implementation, loggerFactory, contextFactory, tracer)
	return serverApp, nil
}
